/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedBookingRouteImport } from './routes/_authenticated/booking'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedConfirmationRouteImport } from './routes/_authenticated/confirmation'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminSalonRouteImport } from './routes/_authenticated/admin.salon'
import { Route as AuthenticatedAdminScheduleRouteImport } from './routes/_authenticated/admin.schedule'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingRoute = AuthenticatedBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfirmationRoute =
  AuthenticatedConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSalonRoute = AuthenticatedAdminSalonRouteImport.update({
  id: '/admin/salon',
  path: '/admin/salon',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminScheduleRoute =
  AuthenticatedAdminScheduleRouteImport.update({
    id: '/admin/schedule',
    path: '/admin/schedule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/admin/services',
    path: '/admin/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/confirmation': typeof AuthenticatedConfirmationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/salon': typeof AuthenticatedAdminSalonRoute
  '/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/booking': typeof AuthenticatedBookingRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/confirmation': typeof AuthenticatedConfirmationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/salon': typeof AuthenticatedAdminSalonRoute
  '/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/booking': typeof AuthenticatedBookingRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/confirmation': typeof AuthenticatedConfirmationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/admin/salon': typeof AuthenticatedAdminSalonRoute
  '/_authenticated/admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/booking'
    | '/checkout'
    | '/confirmation'
    | '/dashboard'
    | '/profile'
    | '/admin/salon'
    | '/admin/schedule'
    | '/admin/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/booking'
    | '/checkout'
    | '/confirmation'
    | '/dashboard'
    | '/profile'
    | '/admin/salon'
    | '/admin/schedule'
    | '/admin/services'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/appointments'
    | '/_authenticated/booking'
    | '/_authenticated/checkout'
    | '/_authenticated/confirmation'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/admin/salon'
    | '/_authenticated/admin/schedule'
    | '/_authenticated/admin/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking': {
      id: '/_authenticated/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof AuthenticatedBookingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/confirmation': {
      id: '/_authenticated/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof AuthenticatedConfirmationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/salon': {
      id: '/_authenticated/admin/salon'
      path: '/admin/salon'
      fullPath: '/admin/salon'
      preLoaderRoute: typeof AuthenticatedAdminSalonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/schedule': {
      id: '/_authenticated/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AuthenticatedAdminScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedBookingRoute: typeof AuthenticatedBookingRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedConfirmationRoute: typeof AuthenticatedConfirmationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminSalonRoute: typeof AuthenticatedAdminSalonRoute
  AuthenticatedAdminScheduleRoute: typeof AuthenticatedAdminScheduleRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedBookingRoute: AuthenticatedBookingRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedConfirmationRoute: AuthenticatedConfirmationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminSalonRoute: AuthenticatedAdminSalonRoute,
  AuthenticatedAdminScheduleRoute: AuthenticatedAdminScheduleRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
